### ISSUE TITLE
custom_data needs to be base64

### ISSUE THREAD

**Issue by JohnDelisle** [stealthllama/terraform-azurerm-panos-bootstrap#2]
I attempted to use your example VM configuration to bootstrap an environment and discovered that you must base64encode() the custom_data content or provisioning fails.

Is there a reference or documentation you can point me to regarding troubleshooting post-provisioning bootstrapping?  I want to know how/where to look to debug bootstrap issues, and how to confirm the custom_data variables are being consumed in the VM correctly.  Thanks

**Comment by mrichardson03** [comment]
So this isn't a bug, but an issue with the documentation?

**Comment by JohnDelisle** [comment]
Splitting hairs, but it's a bug in the terraform that's part of the documentation, so.. both? Neither? :)

**Comment by mrichardson03** [comment]
Is the issue with the Azure resources created by this Terraform module, or solely with the sample Terraform code contained in the Utilization section of README.md?
